export const DefaultInputs = {
  fields: [
    {
      controlType: "input",
      inputType: "text",
      label: "Full Name",
      name: "fullName",
      placeholder: "Enter full name",
      required: true,
    },
    {
      controlType: "input",
      inputType: "email",
      label: "Email",
      name: "email",
      placeholder: "Enter email",
      required: true,
    },
    {
      controlType: "input",
      inputType: "password",
      label: "Password",
      name: "password",
      placeholder: "Enter password",
      required: true,
      minLength: 6,
    },
    {
      controlType: "input",
      inputType: "number",
      label: "Age",
      name: "age",
      min: 1,
      max: 100,
      step: 1,
    },
    {
      controlType: "input",
      inputType: "tel",
      label: "Phone",
      name: "phone",
      placeholder: "Enter phone number",
    },
    {
      controlType: "input",
      inputType: "url",
      label: "Website",
      name: "website",
      placeholder: "https://example.com",
    },
    {
      controlType: "input",
      inputType: "date",
      label: "Date of Birth",
      name: "dob",
    },
    {
      controlType: "input",
      inputType: "time",
      label: "Preferred Time",
      name: "time",
    },
    {
      controlType: "input",
      inputType: "datetime-local",
      label: "Meeting Date",
      name: "meeting",
    },
    {
      controlType: "input",
      inputType: "color",
      label: "Favorite Color",
      name: "color",
    },
    {
      controlType: "file",
      label: "Upload Resume",
      name: "resume",
      accept: ".pdf,.doc,.docx",
      multiple: false,
    },
    {
      controlType: "range",
      label: "Expected Salary",
      name: "salary",
      min: 10000,
      max: 100000,
      step: 1000,
    },
    {
      controlType: "radio",
      label: "Gender",
      name: "gender",
      options: [
        { label: "Male", value: "male" },
        { label: "Female", value: "female" },
        { label: "Other", value: "other" },
      ],
    },
    {
      controlType: "select",
      label: "Country",
      name: "country",
      options: [
        { label: "India", value: "india" },
        { label: "USA", value: "usa" },
        { label: "Canada", value: "canada" },
      ],
    },
    {
      controlType: "select",
      label: "Skills",
      name: "skills",
      multiple: true,
      options: [
        { label: "React", value: "react" },
        { label: "Node", value: "node" },
        { label: "Java", value: "java" },
      ],
    },
    {
      controlType: "checkbox",
      label: "Accept Terms",
      name: "terms",
      required: true,
    },
    {
      controlType: "textarea",
      label: "About You",
      name: "about",
      rows: 4,
      placeholder: "Tell us about yourself",
    },
    {
      controlType: "button",
      label: "Submit",
      name: "submitBtn",
      buttonType: "submit",
      variant: "primary",
      classname: "",
    },
    {
      controlType: "button",
      label: "Reset",
      name: "resetBtn",
      buttonType: "reset",
      variant: "secondary",
    },
  ],
};
